name: Main workflow - build & release
on: [ push, pull_request ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Run mvn verify
        run: mvn --batch-mode --update-snapshots verify
      - name: Uploading jar
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v2
        with:
          name: Jar file
          path: target/*.jar
          retention-days: 1
  release:
    name: Release artifacts
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved jar
        uses: actions/download-artifact@v2
        with:
          name: Jar file
          path: .
      - name: Create release with jar asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./*.jar
